server:
  port: ${PORT:7700}

spring:
  application:
    name: uaa
#store
  datasource:
    url: jdbc:mysql://localhost/skill_share
    username: root
    password: 
    driver-class: com.mysql.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
